image: node:11.6.0

cache:
  key: node_modules
  paths:
    - node_modules

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules

deploy_development:
  stage: deploy
  only:
    - master
  script:
    - export SSHPASS=$DEV_PASS
    - sshpass -e ssh -o "StrictHostKeyChecking=no" $DEV_HOST "cd $DEV_PATH && git checkout . && git pull"
    - sshpass -e ssh -o "StrictHostKeyChecking=no" $DEV_HOST "cd $DOCKER_PATH && docker-compose up -d --build $DEV_NAME"

deploy_production:
  stage: deploy
  only:
    - production
  script:
    - export SSHPASS=$PROD_PASS
    - sshpass -e ssh -o "StrictHostKeyChecking=no" $PROD_HOST "cd $PROD_PATH && git checkout . && git pull"
    - sshpass -e ssh -o "StrictHostKeyChecking=no" $PROD_HOST "cd $DOCKER_PATH && docker-compose up -d --build $PROD_NAME"