

export const SET_COMPETENCYS  = "SET_COMPETENCYS";
export const ADD_COMPETENCYS  = "ADD_COMPETENCYS";
export const SET_COMPETENCY_COMPANY_MASTER  = "SET_COMPETENCY_COMPANY_MASTER";
export const SET_COMPETENCY_RANK_MASTER  = "SET_COMPETENCY_RANK_MASTER";
export const SET_COMPETENCY_MAJOR_MASTER  = "SET_COMPETENCY_MAJOR_MASTER";
export const SET_COMPETENCY_WORKSCORE_MASTER  = "SET_COMPETENCY_WORKSCORE_MASTER";
export const SET_COMPETENCY  = "SET_COMPETENCY";
export const EDIT_COMPETENCY  = "EDIT_COMPETENCY";
export const ADD_COMPETENCY  = "ADD_COMPETENCY";
export const VIEW_COMPETENCY  = "VIEW_COMPETENCY";


const initState = {
    competencys: [],
    competency: {
        mode: VIEW_COMPETENCY,
       
    },
    
};
